# Generated by Django 5.2.11 on 2026-02-10 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_connectionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='administered_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
